## With PostgreSQL and pgAdmin 4.18
# version: "3"

# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: pass123
#     ports:
#       - "5432:5432"
#   pgadmin:
#     image: dpage/pgadmin4:4.18
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
#       PGADMIN_DEFAULT_PASSWORD: secret
#       PGADMIN_LISTEN_PORT: 80
#     ports:
#       - "8080:5050"
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin
#     links:
#       - "db:pgsql-server"

# volumes:
#   db-data:
#   pgadmin-data:

version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"