version: "3.9"

services:

  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: mysql:8.0.23
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
      MYSQL_ROOT_PASSWORD: develop
      MYSQL_DATABASE: adminapp
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - database
