version: "3.9"

services:

  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - ./:/app
    depends_on:
      - database

  database:
    image: mariadb:10.6.2-focal
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: adminapp
      MARIADB_USER: adminapp
      MARIADB_PASSWORD: adminapp
    # volumes:
    #   - ./.dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  # Use "database" as host
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
